#!/usr/bin/env python3
"""
PlutoSDR VNA Data Plotter - GPR Target Detection Viewer
=======================================================
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tkinter as tk
from tkinter import filedialog
import sys
import os

def main():
    root = tk.Tk()
    root.withdraw()

    file_path = filedialog.askopenfilename(
        title="Select VNA Detection CSV",
        filetypes=[("CSV Files", "*.csv"), ("All Files", "*.*")]
    )

    if not file_path:
        sys.exit(0)

    try:
        df = pd.read_csv(file_path)
    except Exception as e:
        print(f"Error reading CSV: {e}")
        sys.exit(1)

    # 1. Extract columns matching the NEW C++ CSV format
    try:
        t = df['Time'].values
        s21_raw = df['S21_dB'].values
        s21_savgol = df['S21_SavGol'].values
        baseline = df['Baseline'].values
        diff_db = df['Diff_dB'].values
        detect_flag = df['Detect_Flag'].values
        minima_flag = df['Minima_Flag'].values
    except KeyError as e:
        print(f"Error: Missing expected column in CSV: {e}")
        print("Make sure you are loading a file generated by the updated C++ program.")
        sys.exit(1)

    # 2. Extract Metadata Changes (OBJ/Height)
    obj_changes = df['OBJ'].ne(df['OBJ'].shift())
    h_changes = df['Height'].ne(df['Height'].shift())
    combined_changes = obj_changes | h_changes
    meta_change_indices = df.index[combined_changes].tolist()
    if 0 in meta_change_indices:
        meta_change_indices.remove(0)

    # 3. Setup Plot (2 Subplots: Signal Tracking & Threshold Trigger)
    fig, (ax_sig, ax_diff) = plt.subplots(2, 1, figsize=(12, 9), sharex=True, gridspec_kw={'height_ratios': [2, 1]})
    
    # --- Top Plot: Signal & Detections ---
    ax_sig.plot(t, s21_raw, '.', color='lightgray', ms=2, alpha=0.4, label='S21 Raw')
    ax_sig.plot(t, s21_savgol, '-', color='dodgerblue', lw=2, label='S21 Filtered (SavGol)')
    ax_sig.plot(t, baseline, '--', color='forestgreen', lw=2, label='Rolling Baseline (Clean)')

    # Highlight Detection Zones
    ax_sig.fill_between(t, ax_sig.get_ylim()[0], ax_sig.get_ylim()[1], 
                        where=(detect_flag == 1), color='red', alpha=0.1, label='Target Zone Active')

    # Mark Minima (Mine Centers)
    minima_times = df[df['Minima_Flag'] == 1]['Time']
    minima_vals = df[df['Minima_Flag'] == 1]['S21_SavGol']
    ax_sig.plot(minima_times, minima_vals, 'rv', markersize=10, markeredgecolor='darkred', label='Minima (Target Center)')

    ax_sig.set_ylabel("S21 Loss (dB)")
    ax_sig.set_title(f"GPR Scan DSP & Detection Log: {os.path.basename(file_path)}")
    ax_sig.grid(True, alpha=0.3)
    ax_sig.legend(loc='lower left')

    # --- Bottom Plot: Difference vs Threshold ---
    ax_diff.plot(t, diff_db, color='purple', lw=1.5, label='Absolute Diff from Baseline')
    ax_diff.axhline(y=5.0, color='red', linestyle='--', lw=2, label='Detection Threshold (5.0 dB)')
    
    # Shade area above threshold
    ax_diff.fill_between(t, 5.0, diff_db, where=(diff_db >= 5.0), color='purple', alpha=0.3)

    ax_diff.set_ylabel("Difference (dB)")
    ax_diff.set_xlabel("Time (seconds)")
    ax_diff.grid(True, alpha=0.3)
    ax_diff.legend(loc='upper right')
    ax_diff.set_ylim(bottom=0) # Lock bottom to 0 for clear viewing

    # 4. Add Markers for Object/Height Changes
    for idx in meta_change_indices:
        change_t = t[idx]
        label_text = f" OBJ:{df['OBJ'].iloc[idx]}\n H:{df['Height'].iloc[idx]}m"
        
        for i, ax in enumerate((ax_sig, ax_diff)):
            ax.axvline(x=change_t, color='orange', linestyle='--', alpha=0.7)
            if i == 0:
                ax.text(change_t, 0.98, label_text, color='darkorange', transform=ax.get_xaxis_transform(),
                        va='top', ha='right', fontsize=8, bbox=dict(boxstyle="round", fc='w', ec='orange', alpha=0.8))

    plt.tight_layout()

    # --- AUTO-SAVE LOGIC ---
    base_path = os.path.splitext(file_path)[0]
    img_path = f"{base_path}.png"

    if not os.path.exists(img_path):
        print(f"Saving plot image to: {img_path}")
        plt.savefig(img_path, dpi=300, bbox_inches='tight')
    else:
        print(f"Image already exists at: {img_path}. Skipping save.")

    # Display the interactive window
    plt.show()

if __name__ == "__main__":
    main()
